# Generated by Django 5.0.6 on 2024-06-06 18:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='city_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='city_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='position_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='position_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='company_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='company_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='fullname_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='fullname_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='question_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='question_ru',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='text_en',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='text_ru',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='jobcategorymodel',
            name='category_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcategorymodel',
            name='category_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobknowledgesmodel',
            name='knowledge_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobknowledgesmodel',
            name='knowledge_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='aboutthejob_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='aboutthejob_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='location_en',
            field=models.CharField(default='Uzbekistan, Tashkent', null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='location_ru',
            field=models.CharField(default='Uzbekistan, Tashkent', null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='requirements_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='requirements_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='responsibilities_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='responsibilities_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='title_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='title_ru',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postcategorymodel',
            name='category_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postcategorymodel',
            name='category_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posttagmodel',
            name='tag_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='posttagmodel',
            name='tag_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='advantages_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='advantages_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='category_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='category_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='company_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='company_ru',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='position_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='position_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
