# Generated by Django 5.0.6 on 2024-06-11 17:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_checkout_address_en_checkout_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='company_ru',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='fullname_ru',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='partnersmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='partnersmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='company_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='position_ru',
        ),
        migrations.CreateModel(
            name='AdminReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.contactusmodel')),
            ],
            options={
                'verbose_name': 'Admin Reply',
                'verbose_name_plural': 'Admin Replies',
                'ordering': ('-id',),
            },
        ),
    ]
