# Generated by Django 5.0.6 on 2024-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_checkout_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
