# Generated by Django 5.0.6 on 2024-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_adminreply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
