# Generated by Django 5.0.6 on 2024-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_adminreply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
