# Generated by Django 5.0.6 on 2024-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_contactusmodel_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
