# Generated by Django 5.0.6 on 2024-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pricingmodel_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='detail_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='detail_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
