# Generated by Django 5.0.6 on 2024-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_pricingmodel_detail_en_pricingmodel_detail_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
