# Generated by Django 5.0.6 on 2024-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_pricingmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
