# Generated by Django 5.0.6 on 2024-07-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_checkout_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='position',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='socail_media',
        ),
    ]
