# Generated by Django 5.0.6 on 2024-07-24 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_position_checkout_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='user',
            field=models.ForeignKey(default='client', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feedbackUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
