# Generated by Django 5.0.6 on 2024-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
