# Generated by Django 5.0.6 on 2024-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_visithistory_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
