# Generated by Django 5.0.6 on 2024-06-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0082_visithistory_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='is_online1',
            field=models.BooleanField(default=False),
        ),
    ]
