# Generated by Django 5.0.6 on 2024-06-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_visithistory_is_online1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visithistory',
            old_name='is_online1',
            new_name='is_user_online',
        ),
    ]
