# Generated by Django 5.0.6 on 2024-06-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_rename_is_online1_visithistory_is_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='is_user_online',
        ),
    ]
