# Generated by Django 5.0.6 on 2024-06-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0085_remove_visithistory_is_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
