# Generated by Django 5.0.6 on 2024-06-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0086_visithistory_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='is_online',
        ),
    ]
