# Generated by Django 5.0.6 on 2024-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_remove_visithistory_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='_visit_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
