# Generated by Django 5.0.6 on 2024-06-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_visithistory__visit_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visithistory',
            old_name='_visit_duration',
            new_name='activity_duration',
        ),
    ]
