# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0089_rename__visit_duration_visithistory_activity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='activity_duration',
        ),
    ]
