# Generated by Django 5.0.6 on 2024-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0090_remove_visithistory_activity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
