# Generated by Django 5.0.6 on 2024-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_remove_projectmodel_link_remove_projectmodel_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
