# Generated by Django 5.0.6 on 2024-06-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0092_alter_projectmodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='created_at',
            new_name='posted_on',
        ),
    ]
